---
kind: pipeline
name: default

steps:
  - name: fetch
    image: plugins/git
    commands:
      - git fetch --tags

  - name: unit_test
    image: golang:1.14
    commands:
      - go test -mod=vendor -v ./...
    when:
      event: [ pull_request, tag ]

  - name: Goreleaser Build
    image: golang:1.14
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: [ tag ]
      status: [ success ]

  - name: Docker Build
    image: plugins/docker
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    settings:
      auto_tag: true
      repo: gmorse81/boondoggle
      build_args_from_env:
        - DRONE_TAG
    when:
      event: [ tag ]
      status: [ success ]

  - name: Goreleaser Build DryRun
    image: golang:1.14
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash -s -- build --skip-validate
    when:
      event: [ pull_request ]
      status: [ success ]

  #- name: Docker Build DryRun
  #  image: plugins/docker
  #  environment:
  #    DOCKER_USERNAME:
  #      from_secret: docker_username
  #    DOCKER_PASSWORD:
  #      from_secret: docker_password
  #  settings:
  #    repo: gmorse81/boondoggle
  #    tags:
  #      - dev
  #  when:
  #    event: [ pull_request ]
  #    status: [ success ]

  # - name: docker_build_latest
  #   image: plugins/docker
  #   environment:
  #     DOCKER_USERNAME:
  #       from_secret: docker_username
  #     DOCKER_PASSWORD:
  #       from_secret: docker_password
  #   settings:
  #     tags:
  #       - latest
  #     repo: gmorse81/boondoggle
  #   when:
  #     event: [ tag ]
  #     status: [ success ]
---
kind: signature
hmac: 143eb058228afbb0460f6d8dd1069463e540c7a87fdb24674a96198948e09f5b

...
