//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoondoggleDeploy) DeepCopyInto(out *BoondoggleDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoondoggleDeploy.
func (in *BoondoggleDeploy) DeepCopy() *BoondoggleDeploy {
	if in == nil {
		return nil
	}
	out := new(BoondoggleDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoondoggleDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoondoggleDeployList) DeepCopyInto(out *BoondoggleDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoondoggleDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoondoggleDeployList.
func (in *BoondoggleDeployList) DeepCopy() *BoondoggleDeployList {
	if in == nil {
		return nil
	}
	out := new(BoondoggleDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoondoggleDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoondoggleDeploySpec) DeepCopyInto(out *BoondoggleDeploySpec) {
	*out = *in
	in.RawBoondoggle.DeepCopyInto(&out.RawBoondoggle)
	if in.StateVersionOverrides != nil {
		in, out := &in.StateVersionOverrides, &out.StateVersionOverrides
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoondoggleDeploySpec.
func (in *BoondoggleDeploySpec) DeepCopy() *BoondoggleDeploySpec {
	if in == nil {
		return nil
	}
	out := new(BoondoggleDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoondoggleDeployStatus) DeepCopyInto(out *BoondoggleDeployStatus) {
	*out = *in
	in.LastDeployTimestamp.DeepCopyInto(&out.LastDeployTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoondoggleDeployStatus.
func (in *BoondoggleDeployStatus) DeepCopy() *BoondoggleDeployStatus {
	if in == nil {
		return nil
	}
	out := new(BoondoggleDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DepValuesAllStates) DeepCopyInto(out *DepValuesAllStates) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DepValuesAllStates.
func (in *DepValuesAllStates) DeepCopy() *DepValuesAllStates {
	if in == nil {
		return nil
	}
	out := new(DepValuesAllStates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environments) DeepCopyInto(out *Environments) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AddtlHelmFlags != nil {
		in, out := &in.AddtlHelmFlags, &out.AddtlHelmFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environments.
func (in *Environments) DeepCopy() *Environments {
	if in == nil {
		return nil
	}
	out := new(Environments)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRepos) DeepCopyInto(out *HelmRepos) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRepos.
func (in *HelmRepos) DeepCopy() *HelmRepos {
	if in == nil {
		return nil
	}
	out := new(HelmRepos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawBoondoggle) DeepCopyInto(out *RawBoondoggle) {
	*out = *in
	if in.HelmRepos != nil {
		in, out := &in.HelmRepos, &out.HelmRepos
		*out = make([]HelmRepos, len(*in))
		copy(*out, *in)
	}
	in.Umbrella.DeepCopyInto(&out.Umbrella)
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]Services, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawBoondoggle.
func (in *RawBoondoggle) DeepCopy() *RawBoondoggle {
	if in == nil {
		return nil
	}
	out := new(RawBoondoggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Services) DeepCopyInto(out *Services) {
	*out = *in
	in.DepValuesAllStates.DeepCopyInto(&out.DepValuesAllStates)
	if in.States != nil {
		in, out := &in.States, &out.States
		*out = make([]States, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Services.
func (in *Services) DeepCopy() *Services {
	if in == nil {
		return nil
	}
	out := new(Services)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *States) DeepCopyInto(out *States) {
	*out = *in
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new States.
func (in *States) DeepCopy() *States {
	if in == nil {
		return nil
	}
	out := new(States)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Umbrella) DeepCopyInto(out *Umbrella) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]Environments, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Umbrella.
func (in *Umbrella) DeepCopy() *Umbrella {
	if in == nil {
		return nil
	}
	out := new(Umbrella)
	in.DeepCopyInto(out)
	return out
}
